[package]
name = "who-is-who"
version = "0.1.0"
edition = "2021"

[dependencies]
axum-macros = "0.4"
axum = { version = "0.8.4", features = ["macros"] }
tokio = { version = "1.45.0", features = ["full"] }
maud = "0.27.0"
serde = { version = "1.0.219", features = ["derive"] }
